# Generated by Django 4.1.5 on 2023-01-17 19:36

import agenda.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('crm', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=50)),
                ('telefone', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=30)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('telefone', models.CharField(max_length=14)),
                ('sexo', models.CharField(choices=[('F', 'F'), ('M', 'M')], default='M', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidade', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeC', models.CharField(max_length=100)),
                ('data', models.DateField(validators=[agenda.models.validarData])),
                ('hora', models.CharField(choices=[('08:00', '08:00 ás 09:00'), ('09:00', '09:00 ás 10:00'), ('10:00', '10:00 ás 11:00'), ('14:00', '14:00 ás 15:00'), ('15:00', '15:00 ás 16:00'), ('16:00', '16:00 ás 17:00')], max_length=20)),
                ('especial', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agenda.especialidade')),
                ('med', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agenda.cadastrar')),
            ],
        ),
        migrations.AddField(
            model_name='cadastrar',
            name='especialidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agenda.especialidade'),
        ),
        migrations.CreateModel(
            name='AgendaM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(validators=[agenda.models.validarData])),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agenda.cadastrar')),
            ],
        ),
    ]
